name: Build and Push Docker Image

on:
  push:
    branches:
    - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: make docker-build

    - name: Push the Docker Image
      run: |
        docker login ${DOCKER_REGISTRY_URL} -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        make docker-push
        RELEASE_TAG=latest make docker-push
      env:
        DOCKER_REGISTRY_URL: docker.pkg.github.com
        DOCKER_USERNAME: sbueringer
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
